# Generated by Django 4.1 on 2022-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_admin_classroom_course_student_teacher_time_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="course_classroom",),
        migrations.AddField(
            model_name="course",
            name="course_classroom",
            field=models.ManyToManyField(to="db.classroom"),
        ),
    ]
