# Generated by Django 4.1 on 2022-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_remove_course_course_classroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="classroom_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
