# Generated by Django 4.1 on 2022-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
