# Generated by Django 4.1 on 2022-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_password",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
